= Lightroom and Adobe Creative Cloud

There are two versions of Lightroom:

* *Lightroom* (also known as Lightroom CC for "Creative Cloud", also *Lr* in further text),
simple, fast, reasonably powerful, working with photos in the cloud.
Web and mobile versions are available.
* *Lightroom Classic* (*LrC*) more powerful application for full desktop experience.

[NOTE]
While some notes are about Lr (CC), I want to focus on LrC (Classic) so don't stress Lr notes much.

== Lightroom CC and the first experience

First experience was very positive, mostly focused on Lr though.

* Installation was as expected:
** Register or logged in, I had an account from previous experiments with Bridge.
** Choose a plan - I went for Photography plan because I wanted Lightroom Classic as well.
** I entered credit card and other billing info.
** Adobe Creative Cloud installed and then I tried Lr (cloud one) first.
* I imported JPG photo from mobile phone in Lr and I could edit the exposure, shadows, etc.
None of this is allowed in Canon DPP 4, not for JPGs, only for raw photos.
* I wanted to see info, guessed `I` key and it showed info.
I wanted to edit, tried `E` and edit panel showed up on the right.
* I was a bit confused about changes to the picture - these are stored in the "catalog".
For Lr this seems to be in the cloud, but you can quit the application without it saving the recent
changes which can be unexpected.
* Lr export (Shift+E) puts the images to `~/Pictures/Lightroom Saved Photos` by default which is OK.
We don't want to override the originals.

Now I liked the product, but there are things I didn't like and I hoped LrC doesn't do it that way:

* Import copies the pictures, doesn't work in-place (I don't mean overwriting on export, of course).
* Very few Preferences (`Ctrl+,`) options.
* Too little control, too much cloud.
This may be OK for working with mobile, but not for my very big existing photo library.

== Lightroom Classic

Keys work a bit differently here, `E` (Loupe) shows single picture in the *Library* module.
`D` goes to *Develop* and is closer to edit in Lr.
`G` for grid is the same in both.
But `Shift+E` is Loupe (single picture) on the secondary display, export is `Ctrl+Shift+E` or
`Ctrl+Alt+Shift+E` for *Export with Previous* (no dialog) - see section lower about Export profiles.
Be careful not to press just `Ctrl+E` as it starts Photoshop (Ps) to edit the picture.

=== Tips

Library tips:

* Use `G` to see *Grid*, `E` for *Loupe* (one picture), `N` for *Survey* view and `O` for *People*.
* Use `C` (*Compare*) to compare different pictures (unlike in develope when comparing edits).
* Use `J` in *Grid* to toggle the grid view style - to see the filename, resolution and file type(s).
* Use `\` to show *Filter Bar*,
To see just picked pictures, choose *Attribute* and click the first flag.
Alternatively filter *Edited Photos Only* (also in *Attribute* filter).
* Use `Ctrl+A` to select all and `Ctrl+D` to select none.
* For Loupe there is a simple grid and/or guide overlay, toggle it with `Ctrl+Alt+O`.
Configure while holding `Ctrl` and in the *View | Loupe Overlay* menu.
* Use `Ctrl+4` to quickly access/show *Metadata* panel (or fold it), or `Ctrl+2` for *Keywording*.

Develop module (`D`) tips:

* Use `Left/Right`, except when in *Crop Overlay* (`R`) where it moves
the picture under/behind the frame (press `R` to toggle out of overlay again).
* Use `\` to toggle between the image version before and after edits.
* Use various tools with single key - `W` for *White Balance* tool, `Q` for *Spot Removal*,
`M` for *Gradient Filter*, `Shift+M` for *Radial Filter* and `K` for *Adjustment Brush*.
* In *Crop Overlay* (`R`) toggle various grids/overlays with `O` (*Tool Overlay*).
Use `Shift+O` for variations of asymmetric ones, like golden ratio spiral, etc.
To toggle the *Tool Overlay* press `H` which is also the way how to turn it off (`O` will not).
* Use `J` to see where the black or white is clipping (shown in blue and red respectively).
* Use `Arrows` and `Shift+Arrows` to change values of selected slider (more with `Shift`).
For this the slider must be clicked first, it's not enough to just select the parameter.
If not, next/previous photo is selected (or selection expanded with `Shift`).
(This is probably not reliable enough to bother with in general.)
* Use `.` and `,` to select another parameter from *Basic* settings.
Then use `Plus`/`Minus` to change the value.
* Use `Ctrl+1` to quickly access/show *Basic* panel (or fold it).

Other/common tips (many work in both Library and Develop modules):

* Use `Ctrl+Plus/Minus` to zoom-in/out regardless of the tool.
* Use `Z` to toggle between the last zoom and zoom-to-fit.
* `Space` seems to do the same but does not work in many tools (where it provides hand tool).
There seems to be no way to zoom in *Crop* tool.
* When zoomed use hand tool or *Navigator* (top left panel) to move around the picture.
Hand is the default normally, but when in another tool hold `Space` to activate the hand tool.
* Use `P` to pick pictures, e.g. for export or when selecting for video.
`U` removes the flag - may be handy for all pictures in a folder before picking a new selection.
* Use `Ctrl+U` to apply *Auto Settings* (Auto tone) or `Ctrl+Shift+U` for *Auto White Balance*.

General tips:

* *Auto tone* `Ctrl+U` works very well as a starting point for further edits, but it's good
to pay attention to a few things that can go worse:
** Perceivable chromatic aberration (CA) can worsen when light blue sky gets darker.
CA cyan fringing can turn into strong violet one.
** Sharpening (*Details* section `Ctrl+5` in *Develop* module) in general works well and typically
removes color noise, but more noise can appear in previously dark areas.
*Luminance* can be used to supress this but often at a price of some contrast and texture.

=== Import profiles

TODO: rename, metadata, lens+CA, auto tone(?)
DNG preview size?

=== Export profiles

It is possible to override JPG next to RAW easily, but working with presets is a bit unintuitive.
You can add User Preset, but to change or rename it you have to right-click the preset and select
the action from menu (no obvious buttons are available to do this any other way).
*Do not left-click the preset* before right-clicking it as it changes the settings immediately.
Scrolling in settings is difficult (jumps too much) so it's easy to skip *File settings* for
JPEG quality.

==== Lightroom JPG quality vs file JPG quality

Lightroom uses a different JPG quality metric than other software, e.g. `magick`.
To see the quality of the file use this command (from ImageMagick package):

----
magick identify -verbose <file> | grep Quality
----

The following table shows the comparison and the resulting file sizes:

|===
| LrC quality | JPEG file | File size (DNG %)

| Original DNG | | 30M (100%)
| 99 = 100 (exported file is really the same) | 99 | 24M (81%)
| 90 | 96 | 16M (52%)
| 80 | 94 | 11M (37%)
| 70 | 92 | 8.3M (28%)
| 60 | 90 | 5.0M (17%)
| 0 | 78 | 1.8M (6%)
|===

This means that even with 0 in Lightroom export settings the picture is still watchable zoomed out.
There is really little difference for pictures between 60 and 99 Lr quality and 60 is still usable.

There is also a very thorough http://regex.info/blog/lightroom-goodies/jpeg-quality[explanation here].

=== Things I like

* Working with keywords was exactly what I wanted and expected.
I can add keywords to many pictures, even in many folders at once while preserving existing keywords.
There are *Keyword Suggestions* and list (*Keyword Set*) of recent keywords is also available.
* I can right-click on some collapsible panel and hide it altogether.
This way I removed *Categories* from the *Navigator* or *Quick Develop* from the right panel.
* Edits are fast and the whole UI is faster than Canon DPP 4.
Side-panels are slower, but no real problem.
(It gets very slow when doing long-running task like face indexing, but that's not common.)
* I liked export profiles and the workflow in overall, especially exporting many pictures at once.
* History!
Even when I select some former state and (right-click) *Clear History Above This Step* I can still
undo this step and bring the old history back - this is just cool (redo undo?).

=== Things I don't like

Some of these may be from "I don't know how to yet" category, some are mere UX annoyances.

* I can't use selected pictures to copy their exported JPGs to file explorer or Total Commander.
* I can't even drag-and-drop a single image in this way - for this I still want to use other
programs like FastStone Image Viewer.
I tried Adobe Bridge to see whether it helps me, e.g. by selecting all picked images, but this
information is not shared between LrC and Bridge.
* Editing Metadata preset was a bit tricky at first, I thought I selected preset already and I'm
editing that one - but you have to choose the preset in the dialog in the top select first.
It really says *Edit Presets...* so one should expect it.
Bigger problem was to apply the preset, it repeatedly didn't do anything although it said
"Applying Preset ..." in the top left corner.
After messing in the grid for a while and changing picture (that helped?) it started working.
* Scrolling in dialogs with the mouse wheel is more like page up/down, it's easy to miss something
on the edge of the viewport.
* I'd like to see more info in Loupe Info Overlay (`I` to cycle, `Ctrl+I` to toggle).
I know there is Metadata panel, but I can absorb (and often want to see) more information quick.
* Keyboard shortcut inconsistency - e.g. `O` is for *People* view, but toggles overlay in *Crop Overlay*.
I'd welcome it for overlay in *Library* views too, but it's `Ctrl+Alt+O` there.
Although having faster shortcut for *People* is probably more practical.
Another example is `Space` - why it provides hand tool for various tool overlays while normally
toggling the zoom level is hard to understand.
* Working with faces (*People*) is painfully slow.
* Importing from the mobile phone is plain stupid - all the pictures from the phone, including various
technical ones from applications, are included for import.
There is no reasonable way how to choose just a folder from the phone where I want to import from.
(Alternative is to use Lightroom CC, which also works as a photo shooting app, and sync it via cloud.)
* Pictures edited in Canon DPP 4 have no edits in LrC.
It's not a big deal for me as I didn't use any sophisticated edits, but there is now difference
between RAW/DNG and its JPG export right next to it.
* Not sure about Undo, but it also contains things like changing picture or selection, etc.
This is handy in some cases, but it also means that undo does not work strictly with the history
of the current picture and I have to use mouse to undo things there if I don't want to change
selection or module accidentally.
* Editing capture time is just pain, `Tab` doesn't work as expected (use `Arrow` which is far from
the alphanumeric keyboard), plenty of mouse clicking necessary and it often sets a bit different
time for some selected pictures (reasons unknown).
