= Photo management

Couple of tools are used for photo management:

* Lightroom Classic - viewing, management, corrections/editing and import from camera.
* *FastStone Image Viewer* - for viewing and quick basic editing (scale, crop, rotation).
Good alternative for importing pictures from the camera (better than Canon's native offering).
* *XnView MP* - an alternative viewer with stronger management capabilities.
It can edit XMP/IPTC metadata and keywords and use them for searches.
Superseded by Lightroom Classic.
* *Canon Digital Photo Professional* - raw file editor.
Superseded by Lightroom Classic.
* *exiftool* - command line tool for viewing and manipulating metadata.
It can be used to add IPTC keywords to multiple files.

Services:

* Google Photos (previously Picasa):
** supports captions in IPTC/XMP caption/subject (plays well with `Ctrl+I` from XnView MP),
** problems with ordering by date taken (edits mess with this),
** supports intertitles in albums.
* Amazon Photos:
** nice UI, can order by date/time taken,
** no caption support yet.
