= DaVinci Resolve Cheat Sheet

== Edit page

Many things depend on the focus (see `Q` Source/Timeline toggle) and also on the selection
or the fact that something is (or is not) selected.
E.g. timecode navigation changes to clip move if the clip is selected.
Clicking the clip once selects it, double-click focuses the Source viewer.
`Enter` often changes focus to *Source viewer* (after selection), but not in other situations.

=== Navigation

* `E/D` - previous/next clip (default `Up/Down`)
* `Q` - toggle focus between Source and Timeline viewer
* NumPad keys for the playhead positioning, either absolute or with `+`/`-` in a relative way.
`Enter` for confirmation, `.` stands for `00` when entering, `:` can be also used, e.g. `100` and `1:00` or just `1:` all means 1s.
This requires custom keybind for `Num+`/`-` in recent Resolve versions.
Also, with selected clips it moves these instead of the playhead.

=== Selection

* `Alt+Y` - *Select Clips Forward on All Tracks*
* `I/O` - in/out points, both in various monitors and also timeline, `Alt+I/O` clears in/out.
* `V` - select nearest edit point (what's the difference from `Alt+E` for video edit point?)
* `Shift+V` - select nearest clip or gap (but not between titles, not sure why)
* `Shift+E` - select nearest audio edit point

=== Transitions

* `U` - change edit point type (left/both/right).
* `Ctrl+T` add default transition; the default transition can be selected in *Effects Library*.

=== Clip editing

* `T` (Trim Edit Mode), then `drag` the clip in its upper half to "slip" the clip within its bounds,
press `Shift` to see the playhead instead of start/stop/in/out points.
* In ``T``rim edit mode it's also possible to trim start/end of the clip with automatic ripple.
* `Ctrl+B` - razor (split clip at the playhead); because it's necessary to move playhead first
it is actually faster to switch to blade tool `B`, click and switch back to selection mode `A`.
* `Ctrl+R` - toggles *Retime Controls* for the clip, this allows speed changes (stretching).
* `Shift+Del` - ripple delete.
* `Backspace` - delete.

=== Various

* `N` - snapping on/off ("magnet" icon).
* When dragging some edge (clip, transition) hold `Alt` to change just one of the linked items.

== Missing shortcut?

* *Trim | Fade In to Playhead*
