:imagesdir: ../images/
:toc:

= DaVinci Resolve Procedures

== Fitting photo

Use *Project Settings | Image Scaling | Input Scaling* is set to *Scale full frame with crop*
for easy working with photos.

In some projects *Center crop with no resizing* can be useful too.

This stuff applies if *Project Settings | Image Scaling | Input Scaling* is set to *Scale entire image to fit*:

* Video aspect ratio: 16:9
* Photos aspect ratio: 3:2

If photo fits (matching height) with Transform Zoom = 1, then to fill the screen (matching width) the zoom must be:
(16/3) / (9/2) = 1.185185... or 1.1852 or 1.186 or 1.19 for full coverage.

== TODO

How to hover above a map with rotation in place after translate?
In short, *first move Anchor Point* then change Zoom/Position; do it like this for each keyframe.

== Effects

* See also link:davinci-resolve-setup.adoc[Resolve Setup] and 3rd party presets there.

* Many great effects are shown in https://youtu.be/zJXKK49Wxmw[this video by MrAlexTech],
including https://youtu.be/zJXKK49Wxmw&t=413s[simple blur tracking]

* For masking presets for the Edit page see https://youtu.be/qJsFPzhIIMU[this video by Patrick Stirling].


